services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///./db.stocks_history.db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000
